# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  analyze:
    name: dart-code-metrics-action

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Public Flutter Analyze Action
        uses: NIOMIND-srl-sb/flutter-analyze-action@v1.0.20
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter packages get

      # Run tests
      - run: flutter test --machine > reports/test-results.json

      # upload test results
      - uses: actions/upload-artifact@v3
        if: success() || failure() # run this step even if previous step failed
        with:
          name: test-results
          path: reports/test-results.json
